### ISSUE TITLE
Remember Tab placement too

### ISSUE THREAD

**Issue by freedimension** [michaelestermann/WindowLayoutManager#10]
As a user with multiple Desktop setups (work, home, laptop only) I really love your little gem here. Thumbs up!

It would be even greater, if it would also take into account the placement of Editor tabs (Settings -> Editor -> General -> Editor Tabs -> Tab placement).

While on my laptop only I want them to be on top and in every other scenario I have enough horizontal space to place them on the left (for better readability).

**Comment by michaelestermann** [comment]
@freedimension Love to hear that the plugin supports your daily work.
Seems to be a useful enhancement, I will take a look into it.

**Comment by freedimension** [comment]
Great. Thx for the feedback. :-)

**Comment by michaelestermann** [comment]
Should work with the latest version. If there are any problems according to this, please reopen the issue again.
