### ISSUE TITLE
Menus are added in German

### ISSUE THREAD

**Issue by Snaptags** [michaelestermann/WindowLayoutManager#14]
In my English WebStorm 2019.3.1 the sub menu are being added in German with broken Umlauts: 
![mixup](https://user-images.githubusercontent.com/1249745/71514060-491f8380-289d-11ea-84ff-7a8da8854c20.png)

The language should default to the WebStorm language instead of the Windows system language.

Plus it might be nice to change the language without having to delete _messages_de.properties_ and recompile :-)

**Comment by Snaptags** [comment]
Workaround: set an environment variable `JAVA_TOOL_OPTIONS` and set its value to `-Duser.language=en-US`

**Comment by michaelestermann** [comment]
@Snaptags I will take a look into this in the upcoming week.
