### ISSUE TITLE
Save/Restore splits

### ISSUE THREAD

**Issue by Snaptags** [michaelestermann/WindowLayoutManager#15]
I wanted to use the different layouts to create a "Test Driven Development" view using two vertically split code windows and the "Run Tool" window at the bottom. Unfortunately WindowLayoutManager (v1.3.1) does not handle the splits when applying layouts.

**Comment by cjkent** [comment]
This would be so useful. I have a big display and a laptop screen. The display is wide enough to have 2 editors side-by-side. The laptop is only wide enough to have a single editor open.

I would love to have a layout saved for each of the displays for when I move a window from one display to the other.

**Comment by michaelestermann** [comment]
At the moment I don't see how to implement such a feature, because the editor needs two files for a split view. It is AFAIK not possible to open an empty split editor. Therefore it is not possible to specify which two files should be opened to get a split view.

**Comment by Snaptags** [comment]
Thanks for replying to this issues.

**Comment by michaelestermann** [comment]
Sorry for the huge delay 👎
