### ISSUE TITLE
Export/Import Layout

### ISSUE THREAD

**Issue by vglad** [michaelestermann/WindowLayoutManager#20]
Any chance to add export/import to be able to copy layout into several different PCs?

**Comment by michaelestermann** [comment]
Nice idea, I already thought about introducing such a feature.
In my opinion there are two possibilities.
1. Export the config in a file and import that file.
2. Copy a string (LZString or so) and import the copied string in the other environment.

I marked it as an enhancement as a possible feature in a upcoming version.
At the moment, you can copy the "layout.xml" stored in the .Rider20xx.x/config/options in the user directory (Windows: %Homepath%) and store it at the same location on the target environment.

**Comment by vglad** [comment]
Thanks Michael,
I am using CLion and I recently discovered "Settings repository" option in it.
If I upload my settings into established repository, install Window layout manager on other PC and download saved settings from repository into new CLion on that PC - all windows layouts copied too.
So, I can say that I have tested copy through Settings repository and it works. 👍
