### ISSUE TITLE
Plugin doesn't save sizes of panes and different windows

### ISSUE THREAD

**Issue by ksimka** [michaelestermann/WindowLayoutManager#22]
I use PhpStorm on two displays: macbook's display and big external display. And the only thing I do when I swith is changing sizes of different panes: on big display I make them wider and higher and for a macbook screen I make them narrower and lower.

So I expected that this plugin will do it for me, but looks like it doesn't. Is this an expected behaviour or am I doing something wrong?

**Comment by michaelestermann** [comment]
@ksimka Thanks for the feedback and sorry for the delayed response. 
At the moment, I creating a new version of the plugin with some enhancements. 
I considered your feedback and added this as a feature. 
I'm not yet ready to release the plugin on the jetbrains plugin market, but you can get a preview, which includes the enhancement, here:
https://ci.appveyor.com/project/michaelestermann/windowlayoutmanager/build/artifacts

**Comment by ksimka** [comment]
@michaelestermann Tried the preview version - works for me, thanks!
