### ISSUE TITLE
Fix Notifications category

### ISSUE THREAD

**Issue by Otiel** [michaelestermann/WindowLayoutManager#30]
The current category used for notifications is `demo.notifications.balloon`.

Could you rename it to "Window layout manager"?

![image](https://user-images.githubusercontent.com/3851902/129203119-0c0ec8fd-b62c-473d-8a6e-6edba8e9deca.png)

In addition, I think the default popup type should be changed from "Sticky balloon" to "Balloon". IMO, there's no need to make these notifications sticky, they're not _that_ important.

**Comment by MartinKolarik** [comment]
> IMO, there's no need to make these notifications sticky, they're not that important.

👍 or better yet they could even be removed completely. Unless there was an error, I see no need for the notification.

**Comment by michaelestermann** [comment]
Changed to balloon in #39
